{"nbformat":4,"nbformat_minor":0,"metadata":{"accelerator":"GPU","colab":{"name":"second_trainer_pcds_images.ipynb","provenance":[],"collapsed_sections":[],"toc_visible":true,"machine_shape":"hm"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.3"}},"cells":[{"cell_type":"code","metadata":{"id":"wuXBzLIbEtsZ"},"source":["# Mount a google drive with the person_detection repository inside from here https://github.com/Yannick947/person_detection"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"j5KSeQKwuZYB","executionInfo":{"status":"ok","timestamp":1603533097204,"user_tz":-120,"elapsed":108874,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"outputId":"15113486-4e77-4f6b-ee68-600b33a2857b","colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!pip install gdown==3.6.4\n","!pip install tensorflow-gpu==2.2.0 --user\n","!pip install keras==2.3.1\n","!pip install efficientnet==1.1.0"],"execution_count":2,"outputs":[{"output_type":"stream","text":["Requirement already satisfied: gdown==3.6.4 in /usr/local/lib/python3.6/dist-packages (3.6.4)\n","Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from gdown==3.6.4) (2.23.0)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from gdown==3.6.4) (4.41.1)\n","Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from gdown==3.6.4) (1.15.0)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->gdown==3.6.4) (2020.6.20)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->gdown==3.6.4) (2.10)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->gdown==3.6.4) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->gdown==3.6.4) (3.0.4)\n","Collecting tensorflow-gpu==2.2.0\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/31/bf/c28971266ca854a64f4b26f07c4112ddd61f30b4d1f18108b954a746f8ea/tensorflow_gpu-2.2.0-cp36-cp36m-manylinux2010_x86_64.whl (516.2MB)\n","\u001b[K     |████████████████████████████████| 516.2MB 29kB/s \n","\u001b[?25hRequirement already satisfied: google-pasta>=0.1.8 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.2.0)\n","Requirement already satisfied: astunparse==1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.6.3)\n","Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.32.0)\n","Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (3.3.0)\n","Collecting tensorflow-estimator<2.3.0,>=2.2.0\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/a4/f5/926ae53d6a226ec0fda5208e0e581cffed895ccc89e36ba76a8e60895b78/tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454kB)\n","\u001b[K     |████████████████████████████████| 460kB 56kB/s \n","\u001b[?25hRequirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.12.1)\n","Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.10.0)\n","Requirement already satisfied: scipy==1.4.1; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.4.1)\n","Collecting tensorboard<2.3.0,>=2.2.0\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/1d/74/0a6fcb206dcc72a6da9a62dd81784bfdbff5fedb099982861dc2219014fb/tensorboard-2.2.2-py3-none-any.whl (3.0MB)\n","\u001b[K     |████████████████████████████████| 3.0MB 46.9MB/s \n","\u001b[?25hRequirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.1.2)\n","Requirement already satisfied: protobuf>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (3.12.4)\n","Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.15.0)\n","Requirement already satisfied: wheel>=0.26; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.35.1)\n","Requirement already satisfied: gast==0.3.3 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (0.3.3)\n","Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.1.0)\n","Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (1.18.5)\n","Requirement already satisfied: h5py<2.11.0,>=2.10.0 in /usr/local/lib/python3.6/dist-packages (from tensorflow-gpu==2.2.0) (2.10.0)\n","Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (0.4.1)\n","Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (50.3.0)\n","Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2.23.0)\n","Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.7.0)\n","Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.17.2)\n","Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (3.2.2)\n","Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/dist-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.0.1)\n","Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.3.0)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (3.0.4)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2.10)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2020.6.20)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (0.2.8)\n","Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (4.1.1)\n","Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (4.6)\n","Requirement already satisfied: importlib-metadata; python_version < \"3.8\" in /usr/local/lib/python3.6/dist-packages (from markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (2.0.0)\n","Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (3.1.0)\n","Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.6/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (0.4.8)\n","Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata; python_version < \"3.8\"->markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2.0) (3.2.0)\n","\u001b[31mERROR: tensorflow 2.3.0 has requirement tensorboard<3,>=2.3.0, but you'll have tensorboard 2.2.2 which is incompatible.\u001b[0m\n","\u001b[31mERROR: tensorflow 2.3.0 has requirement tensorflow-estimator<2.4.0,>=2.3.0, but you'll have tensorflow-estimator 2.2.0 which is incompatible.\u001b[0m\n","Installing collected packages: tensorflow-estimator, tensorboard, tensorflow-gpu\n","\u001b[33m  WARNING: The script tensorboard is installed in '/root/.local/bin' which is not on PATH.\n","  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\n","\u001b[33m  WARNING: The scripts estimator_ckpt_converter, saved_model_cli, tensorboard, tf_upgrade_v2, tflite_convert, toco and toco_from_protos are installed in '/root/.local/bin' which is not on PATH.\n","  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\n","Successfully installed tensorboard-2.2.2 tensorflow-estimator-2.2.0 tensorflow-gpu-2.2.0\n","Collecting keras==2.3.1\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/ad/fd/6bfe87920d7f4fd475acd28500a42482b6b84479832bdc0fe9e589a60ceb/Keras-2.3.1-py2.py3-none-any.whl (377kB)\n","\u001b[K     |████████████████████████████████| 378kB 6.3MB/s \n","\u001b[?25hRequirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.6/dist-packages (from keras==2.3.1) (1.4.1)\n","Collecting keras-applications>=1.0.6\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl (50kB)\n","\u001b[K     |████████████████████████████████| 51kB 4.8MB/s \n","\u001b[?25hRequirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras==2.3.1) (1.18.5)\n","Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras==2.3.1) (3.13)\n","Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras==2.3.1) (2.10.0)\n","Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from keras==2.3.1) (1.1.2)\n","Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from keras==2.3.1) (1.15.0)\n","Installing collected packages: keras-applications, keras\n","  Found existing installation: Keras 2.4.3\n","    Uninstalling Keras-2.4.3:\n","      Successfully uninstalled Keras-2.4.3\n","Successfully installed keras-2.3.1 keras-applications-1.0.8\n","Collecting efficientnet==1.1.0\n","  Downloading https://files.pythonhosted.org/packages/28/91/67848a143b54c331605bfba5fd31cf4e9db13d2e429d103fe807acc3bcf4/efficientnet-1.1.0-py3-none-any.whl\n","Requirement already satisfied: scikit-image in /usr/local/lib/python3.6/dist-packages (from efficientnet==1.1.0) (0.16.2)\n","Requirement already satisfied: keras-applications<=1.0.8,>=1.0.7 in /usr/local/lib/python3.6/dist-packages (from efficientnet==1.1.0) (1.0.8)\n","Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image->efficientnet==1.1.0) (3.2.2)\n","Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image->efficientnet==1.1.0) (1.4.1)\n","Requirement already satisfied: pillow>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image->efficientnet==1.1.0) (7.0.0)\n","Requirement already satisfied: PyWavelets>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image->efficientnet==1.1.0) (1.1.1)\n","Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image->efficientnet==1.1.0) (2.4.1)\n","Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.6/dist-packages (from scikit-image->efficientnet==1.1.0) (2.5)\n","Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras-applications<=1.0.8,>=1.0.7->efficientnet==1.1.0) (1.18.5)\n","Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras-applications<=1.0.8,>=1.0.7->efficientnet==1.1.0) (2.10.0)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.1.0) (1.2.0)\n","Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.1.0) (2.4.7)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.1.0) (0.10.0)\n","Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.1.0) (2.8.1)\n","Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx>=2.0->scikit-image->efficientnet==1.1.0) (4.4.2)\n","Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from h5py->keras-applications<=1.0.8,>=1.0.7->efficientnet==1.1.0) (1.15.0)\n","Installing collected packages: efficientnet\n","Successfully installed efficientnet-1.1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"KW6Cre21sZqg","executionInfo":{"status":"ok","timestamp":1603533121394,"user_tz":-120,"elapsed":52627,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"outputId":"abbad976-f77a-44a9-ca30-ab7f37f2b71a","colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["%cd ../../../../content\n","!git clone https://github.com/Yannick947/keras-retinanet.git --branch master\n","%cd keras-retinanet/\n","!pip install .\n","!python setup.py build_ext --inplace\n","%cd ../sample_data/\n","!git clone https://github.com/Yannick947/pcds_images.git\n","%cd ../../"],"execution_count":3,"outputs":[{"output_type":"stream","text":["/content\n","Cloning into 'keras-retinanet'...\n","remote: Enumerating objects: 129, done.\u001b[K\n","remote: Counting objects: 100% (129/129), done.\u001b[K\n","remote: Compressing objects: 100% (94/94), done.\u001b[K\n","remote: Total 6619 (delta 74), reused 80 (delta 34), pack-reused 6490\u001b[K\n","Receiving objects: 100% (6619/6619), 55.97 MiB | 19.89 MiB/s, done.\n","Resolving deltas: 100% (4036/4036), done.\n","/content/keras-retinanet\n","Processing /content/keras-retinanet\n","Requirement already satisfied: keras in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (2.3.1)\n","Collecting keras-resnet==0.1.0\n","  Downloading https://files.pythonhosted.org/packages/05/46/ad0b2d1a05d9497bd80c98a2c3f4d8be38a4601ace69af72814f5fafd851/keras-resnet-0.1.0.tar.gz\n","Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (1.15.0)\n","Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (1.4.1)\n","Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (0.29.21)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (7.0.0)\n","Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (4.1.2.30)\n","Requirement already satisfied: progressbar2 in /usr/local/lib/python3.6/dist-packages (from keras-retinanet==0.5.1) (3.38.0)\n","Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras->keras-retinanet==0.5.1) (3.13)\n","Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.6/dist-packages (from keras->keras-retinanet==0.5.1) (1.18.5)\n","Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.6/dist-packages (from keras->keras-retinanet==0.5.1) (1.0.8)\n","Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras->keras-retinanet==0.5.1) (2.10.0)\n","Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/dist-packages (from keras->keras-retinanet==0.5.1) (1.1.2)\n","Requirement already satisfied: python-utils>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from progressbar2->keras-retinanet==0.5.1) (2.4.0)\n","Building wheels for collected packages: keras-retinanet, keras-resnet\n","  Building wheel for keras-retinanet (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for keras-retinanet: filename=keras_retinanet-0.5.1-cp36-cp36m-linux_x86_64.whl size=184380 sha256=feaad3c67958ae0f9ce217c9d9ffdc85719728341a8155bd280416c9bbb8e3e7\n","  Stored in directory: /root/.cache/pip/wheels/b2/9f/57/cb0305f6f5a41fc3c11ad67b8cedfbe9127775b563337827ba\n","  Building wheel for keras-resnet (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for keras-resnet: filename=keras_resnet-0.1.0-py2.py3-none-any.whl size=13345 sha256=a0d965d1a23bedc7c2d0d63f377a0cd71899e5f4f097c3a6aed9ef5dc0500b97\n","  Stored in directory: /root/.cache/pip/wheels/80/dd/ac/842235b63dddac12faa4b48ebe58b8944e8c2e57c2e38dddb6\n","Successfully built keras-retinanet keras-resnet\n","Installing collected packages: keras-resnet, keras-retinanet\n","Successfully installed keras-resnet-0.1.0 keras-retinanet-0.5.1\n","running build_ext\n","skipping 'keras_retinanet/utils/compute_overlap.c' Cython extension (up-to-date)\n","building 'keras_retinanet.utils.compute_overlap' extension\n","creating build\n","creating build/temp.linux-x86_64-3.6\n","creating build/temp.linux-x86_64-3.6/keras_retinanet\n","creating build/temp.linux-x86_64-3.6/keras_retinanet/utils\n","x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c keras_retinanet/utils/compute_overlap.c -o build/temp.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.o\n","In file included from \u001b[01m\u001b[K/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0\u001b[m\u001b[K,\n","                 from \u001b[01m\u001b[K/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12\u001b[m\u001b[K,\n","                 from \u001b[01m\u001b[K/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/arrayobject.h:4\u001b[m\u001b[K,\n","                 from \u001b[01m\u001b[Kkeras_retinanet/utils/compute_overlap.c:598\u001b[m\u001b[K:\n","\u001b[01m\u001b[K/usr/local/lib/python3.6/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2:\u001b[m\u001b[K \u001b[01;35m\u001b[Kwarning: \u001b[m\u001b[K#warning \"Using deprecated NumPy API, disable it with \" \"#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [\u001b[01;35m\u001b[K-Wcpp\u001b[m\u001b[K]\n"," #\u001b[01;35m\u001b[Kwarning\u001b[m\u001b[K \"Using deprecated NumPy API, disable it with \" \\\n","  \u001b[01;35m\u001b[K^~~~~~~\u001b[m\u001b[K\n","creating build/lib.linux-x86_64-3.6\n","creating build/lib.linux-x86_64-3.6/keras_retinanet\n","creating build/lib.linux-x86_64-3.6/keras_retinanet/utils\n","x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.o -o build/lib.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.cpython-36m-x86_64-linux-gnu.so\n","copying build/lib.linux-x86_64-3.6/keras_retinanet/utils/compute_overlap.cpython-36m-x86_64-linux-gnu.so -> keras_retinanet/utils\n","/content/sample_data\n","Cloning into 'pcds_images'...\n","remote: Enumerating objects: 1201, done.\u001b[K\n","remote: Counting objects: 100% (1201/1201), done.\u001b[K\n","remote: Compressing objects: 100% (1200/1200), done.\u001b[K\n","remote: Total 1201 (delta 3), reused 1195 (delta 1), pack-reused 0\u001b[K\n","Receiving objects: 100% (1201/1201), 51.15 MiB | 20.66 MiB/s, done.\n","Resolving deltas: 100% (3/3), done.\n","/\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"R3NuDVJVl-NU","executionInfo":{"status":"ok","timestamp":1603533125890,"user_tz":-120,"elapsed":3033,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"outputId":"25132c27-407c-4b4f-ebe7-e4159264ca64","colab":{"base_uri":"https://localhost:8080/","height":34}},"source":["import numpy as np\n","import tensorflow as tf\n","import pandas as pd\n","import os\n","from time import gmtime, strftime\n","\n","from keras_retinanet import models\n","from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image\n","from keras_retinanet.utils.visualization import draw_box, draw_caption\n","from keras_retinanet.utils.colors import label_color\n","\n","annot_train_path = '/content/keras-retinanet/annotations/annot_train_pcds.csv'\n","annot_test_path = '/content/keras-retinanet/annotations/annot_test_pcds.csv'\n","classes_path = '/content/keras-retinanet/annotations/classes_filtered.csv'\n","HEADER= ['image_name', 'x1', 'y1', 'x2', 'y2', 'label']\n","df_train = pd.read_csv(annot_train_path, names=HEADER)\n","num_train_images = len(df_train.image_name.unique())\n","print('Number of training images: ', num_train_images)"],"execution_count":4,"outputs":[{"output_type":"stream","text":["Number of training images:  486\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"J8LEtNbNn7Ri"},"source":["# Training\n","\n"]},{"cell_type":"code","metadata":{"id":"A-DO3mGwqq0i","executionInfo":{"status":"ok","timestamp":1603533125892,"user_tz":-120,"elapsed":1572,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}}},"source":["#Paths to pretrained COCO weights\n","PRETRAINED_RES50_VANILLA = '/content/drive/My\\ Drive/person_detection/keras-retinanet/snapshots/resnet50_vanilla.h5'\n","PRETRAINED_RES152_VANILLA = '' # Download official weights if desired\n","# Path to save snapshots\n","SNAPSHOT_PATH = '/content/drive/My\\ Drive/person_detection/keras-retinanet/snapshots_pcds/'\n","#resnet50, map69, standard resize, no augmentation, lr 1e-5\n","PRETRAINED_MODEL_WI = '/content/drive/My\\ Drive/person_detection/keras-retinanet/snapshots_pcds/22-05-2020_071626_resnet50_20_mAP69.h5'"],"execution_count":5,"outputs":[]},{"cell_type":"code","metadata":{"id":"_HLDQdM_yFkX","executionInfo":{"status":"ok","timestamp":1603533234772,"user_tz":-120,"elapsed":30918,"user":{"displayName":"horst hammer","photoUrl":"","userId":"16387219538505432860"}},"outputId":"4c9399cd-cf38-4afd-f2ca-165f1c9241ee","colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["%cd /content/keras-retinanet/\n","for _ in range(10):\n","\n","  logdir = '/content/drive/My\\ Drive/person_detection/keras-retinanet/tensorboard_pcds/{}_2'.format(strftime(\"%Y-%m-%d-%H-%M-%S\", gmtime()))\n","  aug = np.random.uniform(low=0.0, high=1.5)\n","  vis_aug = np.random.uniform(low=0.0, high=2.0)\n","  lr = np.random.uniform(low=3e-4, high=5e-6)\n","\n","  print('Training for following parameters: \\nVisual augmentation factor: {} \\nAugmentation factor: {}, \\nlr: {}'.format(vis_aug, aug, lr))\n","  !python keras_retinanet/bin/train.py  --weights {PRETRAINED_RES50_VANILLA}\\\n","                                        --lr $lr\\\n","                                        --batch-size 2\\\n","                                        --backbone 'resnet50'\\\n","                                        --steps 500\\\n","                                        --epochs 12 \\\n","                                        --weighted-average\\\n","                                        --random-transform\\\n","                                        --visual-aug-factor $vis_aug\\\n","                                        --augmentation-factor $aug\\\n","                                        --tensorboard-dir {logdir}\\\n","                                        --compute-val-loss\\\n","                                        --workers 0\\\n","                                        --no-snapshots\\\n","                                        --multiprocessing\\\n","                                        --max-queue-size 16\\\n","                                        --num-train-imgs 500\\\n","                                        csv /content/keras-retinanet/annotations/annot_train_pcds.csv /content/keras-retinanet/annotations/classes.csv\\\n","                                        --val-annotations /content/keras-retinanet/annotations/annot_test_pcds.csv\\\n","\n","%cd ../../../../../"],"execution_count":7,"outputs":[{"output_type":"stream","text":["/content/keras-retinanet\n","Training for following parameters: \n","Visual augmentation factor: 1.3196258283463558 \n","Augmentation factor: 0.31779810421562216, \n","lr: 7.165848883637022e-05\n","Using TensorFlow backend.\n","/content/keras-retinanet/annotations/annot_test_pcds.csv\n","Creating model, this may take a second...\n","2020-10-24 09:53:29.163039: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-10-24 09:53:29.220111: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:29.221001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:29.221311: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:29.475029: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:29.610989: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:29.643841: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:29.897980: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:29.954909: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:30.462149: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:30.462375: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.463427: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.464341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:30.464685: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-10-24 09:53:30.470098: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-10-24 09:53:30.470516: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a212c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:30.470547: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-10-24 09:53:30.589780: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.590964: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a21d40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:30.591003: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-10-24 09:53:30.592346: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.593337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:30.593405: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:30.593446: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:30.593472: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:30.593499: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:30.593529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:30.593554: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:30.593580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:30.593688: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.594581: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.595402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:30.595503: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:30.597176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-10-24 09:53:30.597211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-10-24 09:53:30.597221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-10-24 09:53:30.597492: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.598419: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:30.599252: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-10-24 09:53:30.599295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 516, in <module>\n","    main()\n","  File \"keras_retinanet/bin/train.py\", line 476, in main\n","    config=args.config\n","  File \"keras_retinanet/bin/train.py\", line 116, in create_models\n","    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)\n","  File \"keras_retinanet/bin/train.py\", line 76, in model_with_weights\n","    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py\", line 492, in load_wrapper\n","    return load_function(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/network.py\", line 1221, in load_weights\n","    with h5py.File(filepath, mode='r') as f:\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 408, in __init__\n","    swmr=swmr)\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 173, in make_fid\n","    fid = h5f.open(name, flags, fapl=fapl)\n","  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n","  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n","  File \"h5py/h5f.pyx\", line 88, in h5py.h5f.open\n","OSError: Unable to open file (unable to open file: name = '/content/drive/My Drive/person_detection/keras-retinanet/snapshots/resnet50_vanilla.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n","Training for following parameters: \n","Visual augmentation factor: 0.22691456213893924 \n","Augmentation factor: 0.5711286583566704, \n","lr: 9.794579051888305e-05\n","Using TensorFlow backend.\n","/content/keras-retinanet/annotations/annot_test_pcds.csv\n","Creating model, this may take a second...\n","2020-10-24 09:53:35.707126: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-10-24 09:53:35.721348: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.722304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:35.722613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:35.724342: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:35.726077: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:35.729896: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:35.731722: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:35.735850: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:35.740338: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:35.740467: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.741495: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.742333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:35.742625: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-10-24 09:53:35.748046: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-10-24 09:53:35.748348: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x296b2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:35.748386: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-10-24 09:53:35.836119: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.837291: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x296bd40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:35.837328: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-10-24 09:53:35.837560: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.838532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:35.838603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:35.838670: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:35.838707: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:35.838734: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:35.838797: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:35.838822: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:35.838848: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:35.838945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.839885: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.840729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:35.840790: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:35.842305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-10-24 09:53:35.842336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-10-24 09:53:35.842346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-10-24 09:53:35.842488: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.843429: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:35.844288: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-10-24 09:53:35.844378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 516, in <module>\n","    main()\n","  File \"keras_retinanet/bin/train.py\", line 476, in main\n","    config=args.config\n","  File \"keras_retinanet/bin/train.py\", line 116, in create_models\n","    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)\n","  File \"keras_retinanet/bin/train.py\", line 76, in model_with_weights\n","    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py\", line 492, in load_wrapper\n","    return load_function(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/network.py\", line 1221, in load_weights\n","    with h5py.File(filepath, mode='r') as f:\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 408, in __init__\n","    swmr=swmr)\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 173, in make_fid\n","    fid = h5f.open(name, flags, fapl=fapl)\n","  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n","  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n","  File \"h5py/h5f.pyx\", line 88, in h5py.h5f.open\n","OSError: Unable to open file (unable to open file: name = '/content/drive/My Drive/person_detection/keras-retinanet/snapshots/resnet50_vanilla.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n","Training for following parameters: \n","Visual augmentation factor: 0.3381302113755378 \n","Augmentation factor: 0.0907187279793713, \n","lr: 0.00011789556093979746\n","Using TensorFlow backend.\n","/content/keras-retinanet/annotations/annot_test_pcds.csv\n","Creating model, this may take a second...\n","2020-10-24 09:53:41.111060: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-10-24 09:53:41.125982: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.126892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:41.127187: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:41.129069: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:41.130820: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:41.131342: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:41.133071: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:41.134285: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:41.138305: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:41.138452: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.139480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.140418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:41.140756: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-10-24 09:53:41.146118: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-10-24 09:53:41.146447: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x271f2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:41.146483: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-10-24 09:53:41.239262: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.240503: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x271fd40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:41.240543: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-10-24 09:53:41.240858: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.241763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:41.241834: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:41.241865: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:41.241891: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:41.241923: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:41.241954: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:41.241983: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:41.242009: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:41.242134: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.243064: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.243903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:41.243966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:41.245463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-10-24 09:53:41.245514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-10-24 09:53:41.245524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-10-24 09:53:41.245707: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.246618: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:41.247460: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-10-24 09:53:41.247518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 516, in <module>\n","    main()\n","  File \"keras_retinanet/bin/train.py\", line 476, in main\n","    config=args.config\n","  File \"keras_retinanet/bin/train.py\", line 116, in create_models\n","    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)\n","  File \"keras_retinanet/bin/train.py\", line 76, in model_with_weights\n","    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py\", line 492, in load_wrapper\n","    return load_function(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/network.py\", line 1221, in load_weights\n","    with h5py.File(filepath, mode='r') as f:\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 408, in __init__\n","    swmr=swmr)\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 173, in make_fid\n","    fid = h5f.open(name, flags, fapl=fapl)\n","  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n","  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n","  File \"h5py/h5f.pyx\", line 88, in h5py.h5f.open\n","OSError: Unable to open file (unable to open file: name = '/content/drive/My Drive/person_detection/keras-retinanet/snapshots/resnet50_vanilla.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n","Training for following parameters: \n","Visual augmentation factor: 0.4949394280513053 \n","Augmentation factor: 0.8613245962811504, \n","lr: 0.00028741938896456213\n","Using TensorFlow backend.\n","/content/keras-retinanet/annotations/annot_test_pcds.csv\n","Creating model, this may take a second...\n","2020-10-24 09:53:46.262764: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-10-24 09:53:46.277219: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.278156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:46.278490: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:46.280409: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:46.282072: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:46.282580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:46.284592: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:46.285858: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:46.289944: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:46.290109: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.291284: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.292322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:46.292769: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-10-24 09:53:46.298229: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-10-24 09:53:46.298545: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2e712c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:46.298588: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-10-24 09:53:46.390892: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.392038: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2e71d40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:46.392106: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-10-24 09:53:46.392402: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.393270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:46.393353: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:46.393378: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:46.393409: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:46.393436: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:46.393467: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:46.393492: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:46.393520: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:46.393614: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.394536: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.395454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:46.395522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:46.397060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-10-24 09:53:46.397094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-10-24 09:53:46.397104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-10-24 09:53:46.397255: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.398264: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:46.399168: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-10-24 09:53:46.399214: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 516, in <module>\n","    main()\n","  File \"keras_retinanet/bin/train.py\", line 476, in main\n","    config=args.config\n","  File \"keras_retinanet/bin/train.py\", line 116, in create_models\n","    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)\n","  File \"keras_retinanet/bin/train.py\", line 76, in model_with_weights\n","    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py\", line 492, in load_wrapper\n","    return load_function(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/network.py\", line 1221, in load_weights\n","    with h5py.File(filepath, mode='r') as f:\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 408, in __init__\n","    swmr=swmr)\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 173, in make_fid\n","    fid = h5f.open(name, flags, fapl=fapl)\n","  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n","  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n","  File \"h5py/h5f.pyx\", line 88, in h5py.h5f.open\n","OSError: Unable to open file (unable to open file: name = '/content/drive/My Drive/person_detection/keras-retinanet/snapshots/resnet50_vanilla.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n","Training for following parameters: \n","Visual augmentation factor: 0.043751687108068094 \n","Augmentation factor: 1.0676060068242197, \n","lr: 0.00010727011310392119\n","Using TensorFlow backend.\n","/content/keras-retinanet/annotations/annot_test_pcds.csv\n","Creating model, this may take a second...\n","2020-10-24 09:53:51.495953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n","2020-10-24 09:53:51.511451: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.512393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:51.512723: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:51.514622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:51.516431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:51.516951: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:51.518739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:51.519915: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:51.523979: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:51.524166: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.525172: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.526056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:51.526385: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n","2020-10-24 09:53:51.532352: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz\n","2020-10-24 09:53:51.532711: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a9f2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:51.532756: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2020-10-24 09:53:51.628484: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.629667: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a9fd40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2020-10-24 09:53:51.629721: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0\n","2020-10-24 09:53:51.629986: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.630919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0\n","coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s\n","2020-10-24 09:53:51.631017: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:51.631058: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10\n","2020-10-24 09:53:51.631102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10\n","2020-10-24 09:53:51.631140: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10\n","2020-10-24 09:53:51.631188: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10\n","2020-10-24 09:53:51.631226: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10\n","2020-10-24 09:53:51.631263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-10-24 09:53:51.631388: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.632373: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.633265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0\n","2020-10-24 09:53:51.633359: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1\n","2020-10-24 09:53:51.634980: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-10-24 09:53:51.635014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 \n","2020-10-24 09:53:51.635030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N \n","2020-10-24 09:53:51.635196: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.636165: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-10-24 09:53:51.637083: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.\n","2020-10-24 09:53:51.637136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15056 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 516, in <module>\n","    main()\n","  File \"keras_retinanet/bin/train.py\", line 476, in main\n","    config=args.config\n","  File \"keras_retinanet/bin/train.py\", line 116, in create_models\n","    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)\n","  File \"keras_retinanet/bin/train.py\", line 76, in model_with_weights\n","    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py\", line 492, in load_wrapper\n","    return load_function(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/engine/network.py\", line 1221, in load_weights\n","    with h5py.File(filepath, mode='r') as f:\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 408, in __init__\n","    swmr=swmr)\n","  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py\", line 173, in make_fid\n","    fid = h5f.open(name, flags, fapl=fapl)\n","  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n","  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n","  File \"h5py/h5f.pyx\", line 88, in h5py.h5f.open\n","OSError: Unable to open file (unable to open file: name = '/content/drive/My Drive/person_detection/keras-retinanet/snapshots/resnet50_vanilla.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)\n","Training for following parameters: \n","Visual augmentation factor: 0.004115489244066017 \n","Augmentation factor: 0.6380904122649255, \n","lr: 0.00023196784426621664\n","Using TensorFlow backend.\n","Traceback (most recent call last):\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 941, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py\", line 74, in <module>\n","    from tensorflow.python.ops.standard_ops import *\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/ops/standard_ops.py\", line 27, in <module>\n","    from tensorflow.python.training.experimental import loss_scaling_gradient_tape\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/training/experimental/loss_scaling_gradient_tape.py\", line 21, in <module>\n","    from tensorflow.python.distribute import distribution_strategy_context\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/distribute/__init__.py\", line 23, in <module>\n","    from tensorflow.python.distribute import cross_device_ops\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_ops.py\", line 28, in <module>\n","    from tensorflow.python.distribute import cross_device_utils\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/distribute/cross_device_utils.py\", line 25, in <module>\n","    from tensorflow.python.distribute import values as value_lib\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/distribute/values.py\", line 25, in <module>\n","    from tensorflow.python.distribute import distribute_lib\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 114, in <module>\n","    from tensorflow.python.distribute import reduce_util\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 659, in _load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 308, in __init__\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 25, in <module>\n","    import keras\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/__init__.py\", line 3, in <module>\n","    from . import utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/__init__.py\", line 6, in <module>\n","    from . import conv_utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/conv_utils.py\", line 9, in <module>\n","    from .. import backend as K\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/backend/__init__.py\", line 1, in <module>\n","    from .load_backend import epsilon\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/backend/load_backend.py\", line 90, in <module>\n","    from .tensorflow_backend import *\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py\", line 5, in <module>\n","    import tensorflow as tf\n","  File \"/root/.local/lib/python3.6/site-packages/tensorflow/__init__.py\", line 41, in <module>\n","    from tensorflow.python.tools import module_util as _module_util\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","KeyboardInterrupt\n","Training for following parameters: \n","Visual augmentation factor: 1.8984610489970644 \n","Augmentation factor: 1.4234018669923376, \n","lr: 2.877679195623697e-05\n","Traceback (most recent call last):\n","  File \"<frozen importlib._bootstrap>\", line 1023, in _handle_fromlist\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py\", line 72, in <module>\n","    from . import numerictypes as nt\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 674, in exec_module\n","  File \"<frozen importlib._bootstrap_external>\", line 764, in get_code\n","  File \"<frozen importlib._bootstrap_external>\", line 832, in get_data\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 25, in <module>\n","    import keras\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/__init__.py\", line 3, in <module>\n","    from . import utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/__init__.py\", line 2, in <module>\n","    from . import np_utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/np_utils.py\", line 6, in <module>\n","    import numpy as np\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/__init__.py\", line 142, in <module>\n","    from . import core\n","  File \"<frozen importlib._bootstrap>\", line 1023, in _handle_fromlist\n","KeyboardInterrupt\n","Training for following parameters: \n","Visual augmentation factor: 0.10811666184447843 \n","Augmentation factor: 0.06225888337485269, \n","lr: 0.00019882348837089677\n","Traceback (most recent call last):\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/usr/lib/python3.6/traceback.py\", line 5, in <module>\n","    import linecache\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 951, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 894, in _find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1157, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1129, in _get_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 1241, in find_spec\n","  File \"<frozen importlib._bootstrap_external>\", line 82, in _path_stat\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 25, in <module>\n","    import keras\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/__init__.py\", line 3, in <module>\n","    from . import utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/__init__.py\", line 2, in <module>\n","    from . import np_utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/np_utils.py\", line 6, in <module>\n","    import numpy as np\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/__init__.py\", line 142, in <module>\n","    from . import core\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/core/__init__.py\", line 103, in <module>\n","    from . import _internal\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/core/_internal.py\", line 11, in <module>\n","    import platform\n","  File \"/usr/lib/python3.6/platform.py\", line 116, in <module>\n","    import sys, os, re, subprocess\n","  File \"/usr/lib/python3.6/subprocess.py\", line 140, in <module>\n","    import threading\n","  File \"/usr/lib/python3.6/threading.py\", line 7, in <module>\n","    from traceback import format_exc as _format_exc\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 152, in __exit__\n","  File \"<frozen importlib._bootstrap>\", line 105, in release\n","KeyboardInterrupt\n","Training for following parameters: \n","Visual augmentation factor: 0.9413644948595115 \n","Augmentation factor: 0.7093401563775554, \n","lr: 7.118039098186736e-05\n","\n","Training for following parameters: \n","Visual augmentation factor: 1.6719825715409453 \n","Augmentation factor: 0.571127610130039, \n","lr: 0.0001709545313700119\n","Traceback (most recent call last):\n","  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n","  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n","  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/__init__.py\", line 2, in <module>\n","    from . import np_utils\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/utils/np_utils.py\", line 6, in <module>\n","    import numpy as np\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/__init__.py\", line 152, in <module>\n","    from . import random\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py\", line 181, in <module>\n","    from . import _pickle\n","  File \"/usr/local/lib/python3.6/dist-packages/numpy/random/_pickle.py\", line 1, in <module>\n","    from .mtrand import RandomState\n","  File \"mtrand.pyx\", line 1, in init numpy.random.mtrand\n","  File \"_bit_generator.pyx\", line 40, in init numpy.random._bit_generator\n","  File \"/usr/lib/python3.6/secrets.py\", line 20, in <module>\n","    from random import SystemRandom\n","  File \"/usr/lib/python3.6/random.py\", line 668, in <module>\n","    class SystemRandom(Random):\n","  File \"/usr/lib/python3.6/random.py\", line 690, in SystemRandom\n","    def seed(self, *args, **kwds):\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"keras_retinanet/bin/train.py\", line 25, in <module>\n","    import keras\n","  File \"/usr/local/lib/python3.6/dist-packages/keras/__init__.py\", line 3, in <module>\n","    from . import utils\n","  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n","  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n","  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n","KeyboardInterrupt\n","/\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"F5VvYnzrdc2k"},"source":["### Anchor Optimization"]},{"cell_type":"code","metadata":{"id":"9gHzgY2kxk9G"},"source":["%cd /content/drive/My Drive/person_detection\n","!git clone https://github.com/martinzlocha/anchor-optimization.git\n","%cd anchor-optimization\n","!pip install .\n","!python setup.py build_ext --inplace"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"TK9l1MUuenkr"},"source":["!pip install tensorflow-gpu==1.15\n","!python ./../anchor-optimization/optimize_anchors.py ./annot_train_filtered_600_2500.csv\n","!pip uninstall tensorflow-gpu==1.15"],"execution_count":null,"outputs":[]}]}